MaxEventSize: 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data.

Writable:
  LogLevel: "INFO"
  InsecureSecrets:
    rtspauth:
      SecretName: rtspauth
      SecretData:
        username: ""
        password: ""

Service:
  Host: "localhost"
  Port: 59983 # Device services are assigned to the 599xx range
  StartupMsg: "device-usb-camera started"

# uncomment when running from command-line in hybrid mode with -cp -o flags
# Clients:
#   core-metadata:
#     Host: "localhost"
# Registry:
#   Host: "localhost"

MessageBus:
  # Host: localhost # uncomment when running from command-line in hybrid mode
  Optional:
    # Default MQTT and NATS Specific options that need to be here to enable environment variable overrides of them
    ClientId: "device-usb-camera"

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"
  # The location of Provision Watcher json files to import when using auto-discovery
  ProvisionWatchersDir: "./res/provisionwatchers"
  Discovery:
    Enabled: true
    Interval: "1h"

Driver:
  # RtspServerMode can be "internal", "external", or "none". Default is "internal" if left blank.
  RtspServerMode: "internal"
  RtspServerExecutable: "./rtsp-simple-server"
  RtspServerHostName: "localhost"
  RtspTcpPort: "8554"
  RtspAuthenticationServer: "localhost:8000"
